name: CI/CT workflow for Rust libraries packaged via cargo

on:
  workflow_dispatch:

jobs:
  ci-ct-job-for-rust-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Rust
        run: |
          sudo apt-get install -y curl build-essential
          sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        working-directory: ./libraries/rust/common-lib
      - name: Run tests
        run: |
          cargo test
        working-directory: ./libraries/rust/common-lib
      - name: Run cargo-audit to check for vulnerabilities in the source code 🔍/🛡️
        run: |
          cargo install cargo-audit
          cargo audit
        working-directory: ./libraries/rust/common-lib
      - name: Create pip package 📦
        run: |
          cargo publish --dry-run
          echo "-------------------------------------------------------------------------------------------------------------------------------------------"
          echo " Print files included in a package"
          cargo package --list
        working-directory: ./libraries/rust/common-lib
      - name: Install CloudSmith dependencies
        run: |
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install --upgrade cloudsmith-cli
      - name: Push cargo package 📦 to CloudSmith. The uniqueness of the package version is essential. 
        # In the context of Cargo and crates published on crates.io, there isn't a specific field or mechanism within Cargo.toml or 
        # the Cargo ecosystem that directly corresponds to a "revision number" separate from the SemVer components (Major, Minor, Patch). 
        # The patch number shall be incremented instead on bug fixes, minor changes in the Cargo.toml file

        # Each version should include (See: https://doc.rust-lang.org/cargo/reference/publishing.html):
        # A changelog entry, preferably manually curated though a generated one is better than nothing
        # A git tag pointing to the published commit
        run: cloudsmith push cargo ${{ secrets.CLOUDSMITH_REPOSITORY }} -k ${{ secrets.CLOUDSMITH_API_KEY }} ./target/package/common_lib-0.1.0.crate
        working-directory: ./libraries/rust/common-lib
