name: CI/CT workflow for C# library nuget packages

on:
  workflow_dispatch:
    
jobs:
  ci-ct-job-for-csharp-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Test with the dotnet CLI
        run: find . -name '*.csproj' -exec dotnet test {} \;
        working-directory: ./libraries/c#/test
      - name: Run Snyk to check for vulnerabilities in the source code 🔍/🛡️
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: ./libraries/c#/src/CommonLib --orgs=${{ secrets.SNYK_ORGANIZATION_ID }} --severity-threshold=high
      - name: Create nuget package 📦. The package version needs to be unique. Therefore the Git run number will be utilized as revision number
        run: |
          export BUILD_VERSION="0.1.0-dev${{ github.run_number }}"
          dotnet pack -c Release
        working-directory: ./libraries/c#/src/CommonLib
      - name: Install CloudSmith dependencies
        run: |
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install --upgrade cloudsmith-cli
      - name: Push nuget package 📦 to CloudSmith. The package version needs to be unique. Therefore the Git run number will be utilized as revision number
        run: |
          export BUILD_VERSION="0.1.0-dev${{ github.run_number }}"
          cloudsmith push nuget ${{ secrets.CLOUDSMITH_REPOSITORY }} -k ${{ secrets.CLOUDSMITH_API_KEY }} ./libraries/c#/src/CommonLib/bin/Release/CommonLib.${BUILD_VERSION}.nupkg
