name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Select service to build'
        required: true
        default: 'go' 
        options:
          - 'go'
          - 'csharp'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push C# ASP .NET Core sample service
        uses: docker/build-push-action@v5
        if: ${{ github.event.inputs.service == 'csharp' }}
        with:
          context: ./backend-services/c#/HelloWorldService
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/csharp-hello-world-service:stable
      - name: Build and push Go Gin sample service
        uses: docker/build-push-action@v5
        if: ${{ github.event.inputs.service == 'go' }}
        with:
          context: ./backend-services/go/hello-world-service
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/go-hello-world-service:stable